# PathFinder Main Notebook

This notebook mirrors `main.py` with a notebook-local training loop that uses `tqdm.auto` so you can watch progress live.


In [1]:
from pathlib import Path

import numpy as np
import torch
import torch.nn.functional as F
from torch.utils.tensorboard import SummaryWriter
from tqdm.auto import tqdm

from evaluate import evaluate, evaluate_top_k
from graph_builder import build_graph
from model import Model
from train import split_data, traintestval_loader, ts_loader

d:\Personal\code\path_model\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
d:\Personal\code\path_model\.venv\Lib\site-packages\torch_geometric\__init__.py:4: UserWarning: An issue occurred while importing 'torch-sparse'. Disabling its usage. Stacktrace: [WinError 127] The specified procedure could not be found
  import torch_geometric.typing


In [2]:
config = {
    "data_dir": "D:/Personal/code/path_model/PathFinder/required_data",
    "output_dir": "output",
    "experiment_name": "hardcoded_shortlist_job_notebook",
    "predict_edge": ("candidature", "has_application", "job"),
    "use_candidature_node": True,
    "use_temporal": True,
    "use_ts_loader": True,
    "ts_nodes_all": True,
    "remove_feat": False,
    "freeze": False,
    "save_model": True,
    "seed": 42,
    "hidden_channels": 64,
    "lr": 1e-4,
    "wd": 1e-5,
    "batch_norm": "layer_norm",
    "linear_unit": "relu",
    "num_layers": 3,
    "conv_operator": "gat",
    "strategy": "uniform",
    "num_neigh": [20, 10],
    "batch_size": 128,
    "eval_batch_size": 3 * 128,
    "train_metric": 0,
    "max_epoch": 30,
    "max_val_decrease": 20,
    "model_list_abl": [1, 1, 1, 1, 1, 1, 1, 1, 1],
    "error_analysis": False,
}

torch.manual_seed(config["seed"])
output_dir = Path(config["output_dir"])
output_dir.mkdir(parents=True, exist_ok=True)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

config


{'data_dir': 'D:/Personal/code/path_model/PathFinder/required_data',
 'output_dir': 'output',
 'experiment_name': 'hardcoded_shortlist_job_notebook',
 'predict_edge': ('candidature', 'has_application', 'job'),
 'use_candidature_node': True,
 'use_temporal': True,
 'use_ts_loader': True,
 'ts_nodes_all': True,
 'remove_feat': False,
 'freeze': False,
 'save_model': True,
 'seed': 42,
 'hidden_channels': 64,
 'lr': 0.0001,
 'wd': 1e-05,
 'batch_norm': 'layer_norm',
 'linear_unit': 'relu',
 'num_layers': 3,
 'conv_operator': 'gat',
 'strategy': 'uniform',
 'num_neigh': [20, 10],
 'batch_size': 128,
 'eval_batch_size': 384,
 'train_metric': 0,
 'max_epoch': 30,
 'max_val_decrease': 20,
 'model_list_abl': [1, 1, 1, 1, 1, 1, 1, 1, 1],
 'error_analysis': False}

In [3]:
def train_notebook(
    model,
    train_loader,
    val_loader,
    test_loader,
    all_data,
    name_experiment,
    strategy,
    output_dir,
    wd=0.00001,
    predict_edge=("candidature", "has_application", "job"),
    num_neigh=None,
    use_ts_loader=True,
    save_model_bool=True    ,
    train_metric=0,
    max_epoch=30,
    max_val_decrease=20,
    lr=0.0001,
    hyperparameters=None,
    error_analysis=False,
):
    if num_neigh is None:
        num_neigh = [20, 10]
    if hyperparameters is None:
        hyperparameters = {}

    writer = SummaryWriter(output_dir + f"/runs/{name_experiment}")
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = model.to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=lr, weight_decay=wd)

    model.train()
    best_metric_early_stop = 100 if train_metric == 0 else -1
    counter = 0

    auc, precision, recall, acc, f1, val_loss = evaluate(model, val_loader, predict_edge=predict_edge)
    writer.add_scalar("Loss/val", val_loss, 0)
    writer.add_scalar("Metrics/auc", auc, 0)
    writer.add_scalar("Metrics/precision", precision, 0)
    writer.add_scalar("Metrics/recall", recall, 0)
    writer.add_scalar("Metrics/accuracy", acc, 0)
    writer.add_scalar("Metrics/F1", f1, 0)

    epoch_bar = tqdm(range(max_epoch), desc="Epochs")
    for epoch in epoch_bar:
        if counter >= max_val_decrease:
            break

        total_loss = 0
        total_examples = 0
        all_batch_size = []

        batch_bar = tqdm(train_loader, leave=False, desc=f"Epoch {epoch:03d}")
        for sampled_data in batch_bar:
            optimizer.zero_grad()
            sampled_data = sampled_data.to(device)
            pred = model(sampled_data)
            ground_truth = sampled_data[predict_edge[0], predict_edge[1], predict_edge[2]].edge_label

            all_batch_size.append(len(ground_truth))

            loss = F.binary_cross_entropy_with_logits(pred.float(), ground_truth.float())
            loss.backward()
            optimizer.step()

            total_loss += float(loss) * pred.numel()
            total_examples += pred.numel()
            batch_bar.set_postfix(loss=float(loss))

        train_loss = total_loss / total_examples
        auc, precision, recall, acc, f1, val_loss = evaluate(model, val_loader, predict_edge=predict_edge)

        writer.add_scalar("Loss/train", train_loss, epoch)
        writer.add_scalar("Loss/val", val_loss, epoch)
        writer.add_scalar("Metrics/auc", auc, epoch)
        writer.add_scalar("Metrics/precision", precision, epoch)
        writer.add_scalar("Metrics/recall", recall, epoch)
        writer.add_scalar("Metrics/accuracy", acc, epoch)
        writer.add_scalar("Metrics/F1", f1, epoch)

        if train_metric == 0:
            metric_early_stop = val_loss
        elif train_metric == 1:
            metric_early_stop = f1
        elif train_metric == 2:
            metric_early_stop = auc
        else:
            metric_early_stop = None

        improved = False
        if train_metric == 0:
            if val_loss < best_metric_early_stop:
                best_metric_early_stop = metric_early_stop
                improved = True
        else:
            if metric_early_stop > best_metric_early_stop:
                best_metric_early_stop = metric_early_stop
                improved = True

        if improved:
            counter = 0
            if save_model_bool:
                Path(output_dir + f"/models_temp/{name_experiment}").mkdir(parents=True, exist_ok=True)
                torch.save(model, output_dir + f"/models_temp/{name_experiment}/model.pt")
        else:
            counter += 1

        epoch_bar.set_postfix(
            train_loss=f"{train_loss:.4f}",
            val_loss=f"{val_loss:.4f}",
            auc=f"{auc:.4f}",
            f1=f"{f1:.4f}",
            patience=f"{counter}/{max_val_decrease}",
        )

        print(
            f"Epoch: {epoch:03d}, Loss: {train_loss:.4f}, "
            f"[Avg,Max,Min] batch size: [{np.mean(all_batch_size):.4f},{np.max(all_batch_size):.4f},{np.min(all_batch_size):.4f}]"
        )

    setting = {"lr": lr}
    setting.update(hyperparameters)
    print("Model trained")

    if save_model_bool:
        model = torch.load(output_dir + f"/models_temp/{name_experiment}/model.pt")

    auc, precision, recall, acc, f1, val_loss = evaluate(model, test_loader, predict_edge=predict_edge)
    precision_at_10, recall_at_10, average_precision_score_at_10, ndcg_score_at_10, mrr, recall_at_10_ts = evaluate_top_k(
        model,
        test_loader,
        all_data,
        name_experiment,
        output_dir=output_dir,
        predict_edge=predict_edge,
        num_neigh=num_neigh,
        ts_loader=use_ts_loader,
        strategy=strategy,
        error_analysis=error_analysis,
    )

    writer.add_hparams(
        setting,
        {
            "hparam/AUC": float(auc),
            "hparam/Precision": float(precision),
            "hparam/Recall": float(recall),
            "hparam/accuracy": float(acc),
            "hparam/F1": float(f1),
            "hparam/val_loss": float(val_loss),
            "precision_at_10": float(precision_at_10),
            "recall_at_10": float(recall_at_10),
            "average_precision_score_at_10": float(average_precision_score_at_10),
            "ndcg_score_at_10": float(ndcg_score_at_10),
            "MRR": float(mrr),
            "recall_at_10_ts": float(recall_at_10_ts),
        },
    )

    print("Model evaluated")
    return model


In [4]:
graph_abl_list = config["model_list_abl"][:8]
use_time_nodes = bool(config["model_list_abl"][8])

data = build_graph(
    config["data_dir"],
    abl_list=graph_abl_list,
    candidature_node=config["use_candidature_node"],
    ts_nodes=config["use_temporal"],
    ts_nodes_all=config["ts_nodes_all"],
    ts_attr=use_time_nodes,
    error_analysis=str(output_dir / "error_analysis" / config["experiment_name"])
    if config["error_analysis"]
    else None,
)
print("Graph built")




Data loaded
Nodes loaded
Edges loaded
Features loaded
Number of edges from candidature to job 53600
min_index :  0
edge_index_candidature_to_job :  tensor([[     0,      1,      2,  ...,  53597,  53598,  53599],
        [ 17817,  67270,  40131,  ..., 131289,  86298, 127635]])
edge_index_user_to_candidature :  tensor([[ 55877,  46906,  77000,  ..., 169669, 115735, 196593],
        [     0,      1,      2,  ...,  53597,  53598,  53599]])
torch.Size([2, 53600])
edge_index_user_to_skill tensor([[     0,      0,      0,  ..., 210248, 210249, 210249],
        [    27,     57,     60,  ...,     47,     51,     47]])
torch.Size([2, 962315])
Graph built


In [5]:
model = Model(
    hidden_channels=config["hidden_channels"],
    data=data,
    remove_feat=config["remove_feat"],
    freeze=config["freeze"],
    list_abl=config["model_list_abl"],
    predict_edge=config["predict_edge"],
    batch_norm=config["batch_norm"],
    linear_unit_label=config["linear_unit"],
    num_layers=config["num_layers"],
    conv_operator=config["conv_operator"],
).to(device)
print("Model instantiated")


Model instantiated


In [6]:
if config["use_ts_loader"]:
    train_loader = ts_loader(
        data,
        0,
        80,
        num_neigh=config["num_neigh"],
        predict_edge=config["predict_edge"],
        strategy=config["strategy"],
        batch_size=config["batch_size"],
    )
    test_loader = ts_loader(
        data,
        90,
        100,
        num_neigh=config["num_neigh"],
        predict_edge=config["predict_edge"],
        strategy=config["strategy"],
        batch_size=config["eval_batch_size"],
    )
    val_loader = ts_loader(
        data,
        80,
        90,
        num_neigh=config["num_neigh"],
        predict_edge=config["predict_edge"],
        strategy=config["strategy"],
        batch_size=config["eval_batch_size"],
    )
else:
    train_data, val_data, test_data = split_data(data, predict_edge=config["predict_edge"])
    train_loader = traintestval_loader(
        train_data,
        num_neigh=config["num_neigh"],
        predict_edge=config["predict_edge"],
        strat=config["strategy"],
        temporal=config["use_temporal"],
        batch_size=config["batch_size"],
        neg_sampling_ratio=1,
    )
    test_loader = traintestval_loader(
        test_data,
        num_neigh=config["num_neigh"],
        predict_edge=config["predict_edge"],
        strat=config["strategy"],
        temporal=config["use_temporal"],
        batch_size=config["eval_batch_size"],
        neg_sampling_ratio=1,
    )
    val_loader = traintestval_loader(
        val_data,
        num_neigh=config["num_neigh"],
        predict_edge=config["predict_edge"],
        strat=config["strategy"],
        temporal=config["use_temporal"],
        batch_size=config["eval_batch_size"],
        neg_sampling_ratio=1,
    )

print("Loaders ready")

edge_label_time : tensor([1704047360, 1704047360, 1704047360,  ..., 1729189760, 1729189760,
        1729189760])
edge_label_time.size() : torch.Size([107200])
edge_label_index[0].size() : torch.Size([107200])
edge_label_index[1].size() : torch.Size([107200])
edge_label_time : tensor([1704047360, 1704047360, 1704047360,  ..., 1729189760, 1729189760,
        1729189760])
edge_label_time.size() : torch.Size([107200])
edge_label_index[0].size() : torch.Size([107200])
edge_label_index[1].size() : torch.Size([107200])
edge_label_time : tensor([1704047360, 1704047360, 1704047360,  ..., 1729189760, 1729189760,
        1729189760])
edge_label_time.size() : torch.Size([107200])
edge_label_index[0].size() : torch.Size([107200])
edge_label_index[1].size() : torch.Size([107200])
Loaders ready


In [7]:
cache_dir = output_dir / 'cache' / config['experiment_name']
cache_dir.mkdir(parents=True, exist_ok=True)

torch.save(data, cache_dir / 'data.pt')
torch.save(train_loader, cache_dir / 'train_loader.pt')
torch.save(val_loader, cache_dir / 'val_loader.pt')
torch.save(test_loader, cache_dir / 'test_loader.pt')

print(f'Cached graph and loaders to {cache_dir}')


Cached graph and loaders to output\cache\hardcoded_shortlist_job_notebook


In [8]:
# cache_dir = output_dir / 'cache' / config['experiment_name']

# data = torch.load(cache_dir / 'data.pt', weights_only=False)
# train_loader = torch.load(cache_dir / 'train_loader.pt', weights_only=False)
# val_loader = torch.load(cache_dir / 'val_loader.pt', weights_only=False)
# test_loader = torch.load(cache_dir / 'test_loader.pt', weights_only=False)

# print(f'Loaded graph and loaders from {cache_dir}')


In [9]:
trained_model = train_notebook(
    model,
    train_loader,
    val_loader,
    test_loader,
    data,
    config["experiment_name"],
    strategy=config["strategy"],
    output_dir=str(output_dir),
    wd=config["wd"],
    predict_edge=config["predict_edge"],
    num_neigh=config["num_neigh"],
    use_ts_loader=config["use_ts_loader"],
    save_model_bool=config["save_model"],
    train_metric=config["train_metric"],
    max_epoch=config["max_epoch"],
    max_val_decrease=config["max_val_decrease"],
    lr=config["lr"],
    hyperparameters=config,
    error_analysis=config["error_analysis"],
)


100%|██████████| 29/29 [00:06<00:00,  4.34it/s]


[0.22622898 0.22614999 0.20356028 ... 0.22305378 0.14208242 0.31590763]
false_positive_rate:  [0.00000000e+00 0.00000000e+00 3.66300366e-04 ... 9.99816850e-01
 9.99816850e-01 1.00000000e+00]
true_positive_rate:  [0.00000000e+00 1.83150183e-04 1.83150183e-04 ... 9.99633700e-01
 1.00000000e+00 1.00000000e+00]
thresholds:  [       inf 0.44730806 0.42845267 ... 0.13193022 0.13149846 0.12804241]

Validation AUC: 0.5119
Validation Precision: 0.5000
Validation Recall: 1.0000
Validation Accuracy: 0.5000
Validation F1: 0.6667
Validation total loss: 0.7007


100%|██████████| 29/29 [00:05<00:00,  5.15it/s]


[0.15271153 0.18477383 0.12668036 ... 0.17742091 0.16979071 0.2026703 ]
false_positive_rate:  [0.00000000e+00 1.83150183e-04 1.83150183e-04 ... 8.97069597e-01
 9.16666667e-01 1.00000000e+00]
true_positive_rate:  [0.00000000e+00 0.00000000e+00 1.83150183e-04 ... 1.00000000e+00
 1.00000000e+00 1.00000000e+00]
thresholds:  [           inf 3.63712817e-01 3.62186044e-01 ... 4.41364199e-02
 1.18485627e-06 0.00000000e+00]

Validation AUC: 0.5488
Validation Precision: 0.5217
Validation Recall: 1.0000
Validation Accuracy: 0.5417
Validation F1: 0.6857
Validation total loss: 0.6924


Epochs:   3%|▎         | 1/30 [02:58<1:26:11, 178.33s/it, auc=0.5488, f1=0.6857, patience=0/20, train_loss=0.6364, val_loss=0.6924]

Epoch: 000, Loss: 0.6364, [Avg,Max,Min] batch size: [127.8234,128.0000,10.0000]


100%|██████████| 29/29 [00:06<00:00,  4.79it/s]


[0.16071323 0.18503687 0.12158306 ... 0.20525162 0.186902   0.22439261]
false_positive_rate:  [0.00000000e+00 0.00000000e+00 1.83150183e-04 ... 8.96520147e-01
 9.09523810e-01 1.00000000e+00]
true_positive_rate:  [0.00000000e+00 1.83150183e-04 1.83150183e-04 ... 1.00000000e+00
 1.00000000e+00 1.00000000e+00]
thresholds:  [           inf 3.55155289e-01 3.52272511e-01 ... 2.52304021e-02
 4.72425090e-05 0.00000000e+00]

Validation AUC: 0.5551
Validation Precision: 0.5237
Validation Recall: 1.0000
Validation Accuracy: 0.5452
Validation F1: 0.6874
Validation total loss: 0.6923


Epochs:   7%|▋         | 2/30 [06:00<1:24:15, 180.57s/it, auc=0.5551, f1=0.6874, patience=0/20, train_loss=0.6316, val_loss=0.6923]

Epoch: 001, Loss: 0.6316, [Avg,Max,Min] batch size: [127.8234,128.0000,10.0000]


Epochs:  10%|█         | 3/30 [09:06<1:22:25, 183.17s/it, auc=0.5555, f1=0.6882, patience=1/20, train_loss=0.6314, val_loss=0.6926]

[0.18115544 0.20859283 0.05786499 ... 0.12428135 0.1445597  0.21438615]
false_positive_rate:  [0.00000000e+00 0.00000000e+00 3.66300366e-04 ... 9.02380952e-01
 9.04578755e-01 1.00000000e+00]
true_positive_rate:  [0.00000000e+00 1.83150183e-04 1.83150183e-04 ... 9.99267399e-01
 9.99267399e-01 1.00000000e+00]
thresholds:  [           inf 5.95471442e-01 5.71576715e-01 ... 3.43446532e-04
 3.92791262e-05 0.00000000e+00]

Validation AUC: 0.5555
Validation Precision: 0.5249
Validation Recall: 0.9993
Validation Accuracy: 0.5473
Validation F1: 0.6882
Validation total loss: 0.6926
Epoch: 002, Loss: 0.6314, [Avg,Max,Min] batch size: [127.8234,128.0000,10.0000]


100%|██████████| 29/29 [00:05<00:00,  5.12it/s]


[0.16225187 0.16048546 0.14327292 ... 0.15293977 0.14685935 0.18321174]
false_positive_rate:  [0.         0.         0.         ... 0.896337   0.89835165 1.        ]
true_positive_rate:  [0.00000000e+00 1.83150183e-04 3.66300366e-04 ... 1.00000000e+00
 1.00000000e+00 1.00000000e+00]
thresholds:  [           inf 5.65144420e-01 5.55243850e-01 ... 1.02658421e-01
 3.42222074e-06 0.00000000e+00]

Validation AUC: 0.5522
Validation Precision: 0.5268
Validation Recall: 1.0000
Validation Accuracy: 0.5508
Validation F1: 0.6900
Validation total loss: 0.6923


Epochs:  13%|█▎        | 4/30 [12:09<1:19:19, 183.05s/it, auc=0.5522, f1=0.6900, patience=0/20, train_loss=0.6310, val_loss=0.6923]

Epoch: 003, Loss: 0.6310, [Avg,Max,Min] batch size: [127.8234,128.0000,10.0000]


Epochs:  17%|█▋        | 5/30 [15:12<1:16:12, 182.89s/it, auc=0.5521, f1=0.6902, patience=1/20, train_loss=0.6311, val_loss=0.6924]

[0.16983837 0.18149593 0.15395571 ... 0.16417633 0.15674742 0.20216049]
false_positive_rate:  [0.         0.         0.         ... 0.89615385 0.8978022  1.        ]
true_positive_rate:  [0.00000000e+00 1.83150183e-04 3.66300366e-04 ... 1.00000000e+00
 1.00000000e+00 1.00000000e+00]
thresholds:  [       inf 0.4931283  0.47260979 ... 0.09933589 0.00132856 0.        ]

Validation AUC: 0.5521
Validation Precision: 0.5269
Validation Recall: 1.0000
Validation Accuracy: 0.5511
Validation F1: 0.6902
Validation total loss: 0.6924
Epoch: 004, Loss: 0.6311, [Avg,Max,Min] batch size: [127.8234,128.0000,10.0000]


Epochs:  20%|██        | 6/30 [18:37<1:16:08, 190.34s/it, auc=0.5506, f1=0.6905, patience=2/20, train_loss=0.6320, val_loss=0.6924]

[0.17758508 0.19083895 0.14573541 ... 0.15653162 0.15773168 0.20322245]
false_positive_rate:  [0.         0.         0.         ... 0.89615385 0.89652015 1.        ]
true_positive_rate:  [0.00000000e+00 1.83150183e-04 7.32600733e-04 ... 1.00000000e+00
 1.00000000e+00 1.00000000e+00]
thresholds:  [       inf 0.51151389 0.45874634 ... 0.0757767  0.00365643 0.        ]

Validation AUC: 0.5506
Validation Precision: 0.5273
Validation Recall: 1.0000
Validation Accuracy: 0.5517
Validation F1: 0.6905
Validation total loss: 0.6924
Epoch: 005, Loss: 0.6320, [Avg,Max,Min] batch size: [127.8234,128.0000,10.0000]


Epochs:  23%|██▎       | 7/30 [21:52<1:13:36, 192.04s/it, auc=0.5545, f1=0.6902, patience=3/20, train_loss=0.6311, val_loss=0.6926]

[0.1669316  0.1739402  0.14782129 ... 0.14172344 0.13906996 0.21486093]
false_positive_rate:  [0.00000000e+00 1.83150183e-04 3.66300366e-04 ... 8.96153846e-01
 8.97619048e-01 1.00000000e+00]
true_positive_rate:  [0. 0. 0. ... 1. 1. 1.]
thresholds:  [       inf 0.75343072 0.7184363  ... 0.03881551 0.00104711 0.        ]

Validation AUC: 0.5545
Validation Precision: 0.5270
Validation Recall: 1.0000
Validation Accuracy: 0.5512
Validation F1: 0.6902
Validation total loss: 0.6926
Epoch: 006, Loss: 0.6311, [Avg,Max,Min] batch size: [127.8234,128.0000,10.0000]


Epochs:  27%|██▋       | 8/30 [24:56<1:09:25, 189.32s/it, auc=0.5528, f1=0.6904, patience=4/20, train_loss=0.6297, val_loss=0.6935]

[0.18470389 0.16066562 0.10449141 ... 0.06151266 0.09830738 0.2166367 ]
false_positive_rate:  [0.00000000e+00 0.00000000e+00 5.49450549e-04 ... 8.96153846e-01
 8.96520147e-01 1.00000000e+00]
true_positive_rate:  [0.00000000e+00 1.83150183e-04 1.83150183e-04 ... 9.99816850e-01
 9.99816850e-01 1.00000000e+00]
thresholds:  [           inf 9.46440101e-01 9.01868463e-01 ... 6.81060506e-03
 8.79489293e-04 0.00000000e+00]

Validation AUC: 0.5528
Validation Precision: 0.5272
Validation Recall: 0.9998
Validation Accuracy: 0.5516
Validation F1: 0.6904
Validation total loss: 0.6935
Epoch: 007, Loss: 0.6297, [Avg,Max,Min] batch size: [127.8234,128.0000,10.0000]


Epochs:  30%|███       | 9/30 [28:46<1:10:43, 202.06s/it, auc=0.5524, f1=0.6904, patience=5/20, train_loss=0.6287, val_loss=0.6942]

[0.09992366 0.12240663 0.10617501 ... 0.01821862 0.0178658  0.14768353]
false_positive_rate:  [0.00000000e+00 0.00000000e+00 7.32600733e-04 ... 8.95238095e-01
 8.95421245e-01 1.00000000e+00]
true_positive_rate:  [0.00000000e+00 1.83150183e-04 1.83150183e-04 ... 9.99267399e-01
 9.99267399e-01 1.00000000e+00]
thresholds:  [           inf 9.99184608e-01 9.77171063e-01 ... 8.76302540e-04
 1.28897605e-04 0.00000000e+00]

Validation AUC: 0.5524
Validation Precision: 0.5274
Validation Recall: 0.9993
Validation Accuracy: 0.5519
Validation F1: 0.6904
Validation total loss: 0.6942
Epoch: 008, Loss: 0.6287, [Avg,Max,Min] batch size: [127.8234,128.0000,10.0000]


Epochs:  33%|███▎      | 10/30 [31:52<1:05:45, 197.27s/it, auc=0.5535, f1=0.6899, patience=6/20, train_loss=0.6277, val_loss=0.6941]

[0.05084994 0.05774813 0.04650515 ... 0.02814258 0.04277685 0.06738429]
false_positive_rate:  [0.00000000e+00 1.83150183e-04 3.66300366e-04 ... 8.92307692e-01
 8.92490842e-01 1.00000000e+00]
true_positive_rate:  [0.         0.         0.         ... 0.99652015 0.99652015 1.        ]
thresholds:  [       inf 0.98434335 0.97818232 ... 0.00441359 0.00427721 0.        ]

Validation AUC: 0.5535
Validation Precision: 0.5275
Validation Recall: 0.9965
Validation Accuracy: 0.5520
Validation F1: 0.6899
Validation total loss: 0.6941
Epoch: 009, Loss: 0.6277, [Avg,Max,Min] batch size: [127.8234,128.0000,10.0000]


Epochs:  37%|███▋      | 11/30 [34:56<1:01:09, 193.11s/it, auc=0.5481, f1=0.6769, patience=7/20, train_loss=0.6266, val_loss=0.6950]

[0.01415532 0.01864153 0.00854073 ... 0.00037433 0.00244775 0.00715529]
false_positive_rate:  [0.00000000e+00 1.83150183e-04 3.66300366e-04 ... 8.55494505e-01
 8.55494505e-01 1.00000000e+00]
true_positive_rate:  [0.         0.         0.         ... 0.94908425 0.9492674  1.        ]
thresholds:  [           inf 9.86445606e-01 9.71522868e-01 ... 2.02930387e-05
 1.49988782e-05 0.00000000e+00]

Validation AUC: 0.5481
Validation Precision: 0.5260
Validation Recall: 0.9493
Validation Accuracy: 0.5469
Validation F1: 0.6769
Validation total loss: 0.6950
Epoch: 010, Loss: 0.6266, [Avg,Max,Min] batch size: [127.8234,128.0000,10.0000]


Epochs:  40%|████      | 12/30 [37:55<56:37, 188.78s/it, auc=0.5321, f1=0.5517, patience=8/20, train_loss=0.6261, val_loss=0.7003]  

[0.10022368 0.         0.19681224 ... 0.         0.         0.13624038]
false_positive_rate:  [0.00000000e+00 1.83150183e-04 1.83150183e-04 ... 5.17216117e-01
 5.17582418e-01 1.00000000e+00]
true_positive_rate:  [0.00000000e+00 0.00000000e+00 1.83150183e-04 ... 5.78021978e-01
 5.78021978e-01 1.00000000e+00]
thresholds:  [           inf 9.85227942e-01 9.82701182e-01 ... 3.43619788e-04
 1.17465706e-05 0.00000000e+00]

Validation AUC: 0.5321
Validation Precision: 0.5276
Validation Recall: 0.5780
Validation Accuracy: 0.5302
Validation F1: 0.5517
Validation total loss: 0.7003
Epoch: 011, Loss: 0.6261, [Avg,Max,Min] batch size: [127.8234,128.0000,10.0000]


Epochs:  43%|████▎     | 13/30 [40:56<52:50, 186.47s/it, auc=0.5274, f1=0.4864, patience=9/20, train_loss=0.6246, val_loss=0.7006]

[0.         0.         0.14211342 ... 0.         0.         0.        ]
false_positive_rate:  [0.00000000e+00 1.83150183e-04 3.66300366e-04 ... 3.91391941e-01
 3.91391941e-01 1.00000000e+00]
true_positive_rate:  [0.         0.         0.         ... 0.44688645 0.4470696  1.        ]
thresholds:  [           inf 9.98990774e-01 9.98519838e-01 ... 4.15927298e-06
 2.65964036e-06 0.00000000e+00]

Validation AUC: 0.5274
Validation Precision: 0.5332
Validation Recall: 0.4471
Validation Accuracy: 0.5278
Validation F1: 0.4864
Validation total loss: 0.7006
Epoch: 012, Loss: 0.6246, [Avg,Max,Min] batch size: [127.8234,128.0000,10.0000]


Epochs:  47%|████▋     | 14/30 [44:02<49:43, 186.50s/it, auc=0.5298, f1=0.5206, patience=10/20, train_loss=0.6241, val_loss=0.7030]

[0.         0.         0.20123066 ... 0.         0.         0.        ]
false_positive_rate:  [0.00000000e+00 1.83150183e-04 1.83150183e-04 ... 4.50915751e-01
 4.51465201e-01 1.00000000e+00]
true_positive_rate:  [0.00000000e+00 0.00000000e+00 1.83150183e-04 ... 5.10805861e-01
 5.10805861e-01 1.00000000e+00]
thresholds:  [           inf 9.98860121e-01 9.97569203e-01 ... 4.62469761e-04
 2.18802484e-06 0.00000000e+00]

Validation AUC: 0.5298
Validation Precision: 0.5308
Validation Recall: 0.5108
Validation Accuracy: 0.5297
Validation F1: 0.5206
Validation total loss: 0.7030
Epoch: 013, Loss: 0.6241, [Avg,Max,Min] batch size: [127.8234,128.0000,10.0000]


Epochs:  50%|█████     | 15/30 [48:01<50:32, 202.16s/it, auc=0.5290, f1=0.5240, patience=11/20, train_loss=0.6245, val_loss=0.7039]

[0.0400633  0.         0.10101071 ... 0.         0.         0.        ]
false_positive_rate:  [0.00000000e+00 1.83150183e-04 3.66300366e-04 ... 4.60622711e-01
 4.61538462e-01 1.00000000e+00]
true_positive_rate:  [0.         0.         0.         ... 0.51886447 0.51886447 1.        ]
thresholds:  [           inf 9.99928355e-01 9.99778271e-01 ... 4.44141711e-04
 1.05559804e-04 0.00000000e+00]

Validation AUC: 0.5290
Validation Precision: 0.5292
Validation Recall: 0.5189
Validation Accuracy: 0.5287
Validation F1: 0.5240
Validation total loss: 0.7039
Epoch: 014, Loss: 0.6245, [Avg,Max,Min] batch size: [127.8234,128.0000,10.0000]


Epochs:  53%|█████▎    | 16/30 [51:41<48:24, 207.44s/it, auc=0.5268, f1=0.5272, patience=12/20, train_loss=0.6217, val_loss=0.7083]

[0.14595145 0.         0.5508693  ... 0.         0.         0.20249194]
false_positive_rate:  [0.         0.         0.         ... 0.47673993 0.47728938 1.        ]
true_positive_rate:  [0.00000000e+00 1.83150183e-04 3.66300366e-04 ... 5.28754579e-01
 5.28754579e-01 1.00000000e+00]
thresholds:  [           inf 9.99983132e-01 9.99944687e-01 ... 7.11613626e-04
 6.35352844e-05 0.00000000e+00]

Validation AUC: 0.5268
Validation Precision: 0.5256
Validation Recall: 0.5288
Validation Accuracy: 0.5257
Validation F1: 0.5272
Validation total loss: 0.7083
Epoch: 015, Loss: 0.6217, [Avg,Max,Min] batch size: [127.8234,128.0000,10.0000]


Epochs:  57%|█████▋    | 17/30 [54:38<42:58, 198.33s/it, auc=0.5241, f1=0.4886, patience=13/20, train_loss=0.6210, val_loss=0.7106]

[0.2110994  0.         0.47851482 ... 0.         0.         0.        ]
false_positive_rate:  [0.00000000e+00 1.83150183e-04 9.15750916e-04 ... 4.06043956e-01
 4.06776557e-01 1.00000000e+00]
true_positive_rate:  [0.        0.        0.        ... 0.4547619 0.4547619 1.       ]
thresholds:  [           inf 9.99973416e-01 9.99464035e-01 ... 5.96927886e-04
 2.00857976e-04 0.00000000e+00]

Validation AUC: 0.5241
Validation Precision: 0.5278
Validation Recall: 0.4548
Validation Accuracy: 0.5240
Validation F1: 0.4886
Validation total loss: 0.7106
Epoch: 016, Loss: 0.6210, [Avg,Max,Min] batch size: [127.8234,128.0000,10.0000]


Epochs:  60%|██████    | 18/30 [57:38<38:33, 192.79s/it, auc=0.5213, f1=0.5004, patience=14/20, train_loss=0.6200, val_loss=0.7172]

[0.         0.         0.37567666 ... 0.         0.         0.        ]
false_positive_rate:  [0.00000000e+00 1.83150183e-04 1.83150183e-04 ... 4.35164835e-01
 4.35164835e-01 1.00000000e+00]
true_positive_rate:  [0.00000000e+00 0.00000000e+00 1.83150183e-04 ... 4.78571429e-01
 4.78937729e-01 1.00000000e+00]
thresholds:  [           inf 1.00000012e+00 9.99999523e-01 ... 3.50949937e-04
 1.39691228e-05 0.00000000e+00]

Validation AUC: 0.5213
Validation Precision: 0.5239
Validation Recall: 0.4789
Validation Accuracy: 0.5219
Validation F1: 0.5004
Validation total loss: 0.7172
Epoch: 017, Loss: 0.6200, [Avg,Max,Min] batch size: [127.8234,128.0000,10.0000]


Epochs:  63%|██████▎   | 19/30 [1:00:38<34:38, 188.95s/it, auc=0.5233, f1=0.4973, patience=15/20, train_loss=0.6205, val_loss=0.7205]

[0.31097394 0.         0.8578265  ... 0.         0.         0.        ]
false_positive_rate:  [0.00000000e+00 1.83150183e-04 5.49450549e-04 ... 4.26190476e-01
 4.26556777e-01 1.00000000e+00]
true_positive_rate:  [0.         0.         0.         ... 0.47216117 0.47216117 1.        ]
thresholds:  [           inf 9.99915123e-01 9.99583185e-01 ... 3.31201172e-03
 9.02056287e-04 0.00000000e+00]

Validation AUC: 0.5233
Validation Precision: 0.5254
Validation Recall: 0.4722
Validation Accuracy: 0.5228
Validation F1: 0.4973
Validation total loss: 0.7205
Epoch: 018, Loss: 0.6205, [Avg,Max,Min] batch size: [127.8234,128.0000,10.0000]


Epochs:  67%|██████▋   | 20/30 [1:03:35<30:54, 185.44s/it, auc=0.5169, f1=0.4828, patience=16/20, train_loss=0.6178, val_loss=0.7239]

[0.         0.         0.77552855 ... 0.         0.         0.        ]
false_positive_rate:  [0.00000000e+00 1.83150183e-04 1.83150183e-04 ... 4.17765568e-01
 4.17765568e-01 1.00000000e+00]
true_positive_rate:  [0.00000000e+00 0.00000000e+00 1.83150183e-04 ... 4.50915751e-01
 4.51098901e-01 1.00000000e+00]
thresholds:  [           inf 9.99861419e-01 9.99860108e-01 ... 9.03163482e-07
 8.91056857e-07 0.00000000e+00]

Validation AUC: 0.5169
Validation Precision: 0.5192
Validation Recall: 0.4511
Validation Accuracy: 0.5167
Validation F1: 0.4828
Validation total loss: 0.7239
Epoch: 019, Loss: 0.6178, [Avg,Max,Min] batch size: [127.8234,128.0000,10.0000]


Epochs:  70%|███████   | 21/30 [1:06:33<27:29, 183.30s/it, auc=0.5218, f1=0.5202, patience=17/20, train_loss=0.6173, val_loss=0.7201]

[0.11360203 0.         0.7782143  ... 0.         0.         0.        ]
false_positive_rate:  [0.00000000e+00 0.00000000e+00 7.32600733e-04 ... 4.74908425e-01
 4.74908425e-01 1.00000000e+00]
true_positive_rate:  [0.00000000e+00 1.83150183e-04 1.83150183e-04 ... 5.17948718e-01
 5.18498168e-01 1.00000000e+00]
thresholds:  [           inf 9.99533296e-01 9.98574913e-01 ... 6.30784605e-04
 2.20721322e-05 0.00000000e+00]

Validation AUC: 0.5218
Validation Precision: 0.5219
Validation Recall: 0.5185
Validation Accuracy: 0.5218
Validation F1: 0.5202
Validation total loss: 0.7201
Epoch: 020, Loss: 0.6173, [Avg,Max,Min] batch size: [127.8234,128.0000,10.0000]


Epochs:  73%|███████▎  | 22/30 [1:09:39<24:33, 184.18s/it, auc=0.5165, f1=0.4498, patience=18/20, train_loss=0.6161, val_loss=0.7127]

[0.427459   0.         0.62432575 ... 0.         0.         0.        ]
false_positive_rate:  [0.         0.         0.         ... 0.36318681 0.36465201 1.        ]
true_positive_rate:  [0.00000000e+00 1.83150183e-04 3.66300366e-04 ... 3.95970696e-01
 3.95970696e-01 1.00000000e+00]
thresholds:  [           inf 9.99955654e-01 9.99909639e-01 ... 1.71581760e-07
 1.88651992e-08 0.00000000e+00]

Validation AUC: 0.5165
Validation Precision: 0.5206
Validation Recall: 0.3960
Validation Accuracy: 0.5157
Validation F1: 0.4498
Validation total loss: 0.7127
Epoch: 021, Loss: 0.6161, [Avg,Max,Min] batch size: [127.8234,128.0000,10.0000]


Epochs:  77%|███████▋  | 23/30 [1:12:52<21:46, 186.63s/it, auc=0.5130, f1=0.4278, patience=19/20, train_loss=0.6149, val_loss=0.7154]

[0.         0.         0.66801333 ... 0.         0.         0.        ]
false_positive_rate:  [0.00000000e+00 1.83150183e-04 9.15750916e-04 ... 3.35531136e-01
 3.35897436e-01 1.00000000e+00]
true_positive_rate:  [0.         0.         0.         ... 0.36355311 0.36355311 1.        ]
thresholds:  [           inf 9.99993503e-01 9.99961138e-01 ... 3.34354118e-05
 3.39773646e-06 0.00000000e+00]

Validation AUC: 0.5130
Validation Precision: 0.5198
Validation Recall: 0.3636
Validation Accuracy: 0.5138
Validation F1: 0.4278
Validation total loss: 0.7154
Epoch: 022, Loss: 0.6149, [Avg,Max,Min] batch size: [127.8234,128.0000,10.0000]


Epochs:  80%|████████  | 24/30 [1:16:05<19:01, 190.23s/it, auc=0.5095, f1=0.3858, patience=20/20, train_loss=0.6141, val_loss=0.7088]


[0. 0. 0. ... 0. 0. 0.]
false_positive_rate:  [0.         0.         0.         ... 0.29047619 0.29047619 1.        ]
true_positive_rate:  [0.00000000e+00 1.83150183e-04 3.66300366e-04 ... 3.08058608e-01
 3.08424908e-01 1.00000000e+00]
thresholds:  [           inf 9.99998748e-01 9.99992311e-01 ... 8.56855479e-07
 1.57363260e-07 0.00000000e+00]

Validation AUC: 0.5095
Validation Precision: 0.5150
Validation Recall: 0.3084
Validation Accuracy: 0.5090
Validation F1: 0.3858
Validation total loss: 0.7088
Epoch: 023, Loss: 0.6141, [Avg,Max,Min] batch size: [127.8234,128.0000,10.0000]
Model trained


UnpicklingError: Weights only load failed. This file can still be loaded, to do so you have two options, do those steps only if you trust the source of the checkpoint. 
	(1) In PyTorch 2.6, we changed the default value of the `weights_only` argument in `torch.load` from `False` to `True`. Re-running `torch.load` with `weights_only` set to `False` will likely succeed, but it can result in arbitrary code execution. Do it only if you got the file from a trusted source.
	(2) Alternatively, to load with `weights_only=True` please check the recommended steps in the following error message.
	WeightsUnpickler error: Unsupported global: GLOBAL model.Model was not an allowed global by default. Please use `torch.serialization.add_safe_globals([model.Model])` or the `torch.serialization.safe_globals([model.Model])` context manager to allowlist this global if you trust this class/function.

Check the documentation of torch.load to learn more about types accepted by default with weights_only https://pytorch.org/docs/stable/generated/torch.load.html.

In [ ]:
from pathlib import Path
import torch

save_dir = Path("output/final_models")
save_dir.mkdir(parents=True, exist_ok=True)

save_path = save_dir / f"{config['experiment_name']}_full_model.pt"
torch.save(trained_model, save_path, pickle_protocol=4)

print(f"Saved full model to: {save_path}")
